name: 15-minute-cron
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call the Scrape API route
        run: |
          curl --request POST \
          --url 'https://tanki-fund-tracker.vercel.app/api/scrape' \
          --header 'Authorization: Bearer ${{ secrets.API_UPDATE_SECRET }}'
